### ISSUE TITLE
Multiple counters via a Declarative approach?

### ISSUE THREAD

**Issue by vilbht** [jaxgeller/counter.js#1]
Hi 

Neat Plugin! Looking at a use case where there are multiple counters (example: http://www.elegantthemes.com/preview/Divi/number-counter/)
Is there a way to make this declarative like:

`<p class = "counter" data-counter="countUp">1000</p>`
`<p class = "counter" data-counter="countDown">1000</p>`

And start counting after it's visible in the viewport?

Thanks
Vilav

**Comment by jaxgeller** [comment]
Yep so just keep making new counters for every counter you want. For example,

``` es6
// opts is ommited for brevity
let a = new Counter(opts1)
let b = new Counter(opts2)
let c = new Counter(opts3)
```

And then you can call those however you'd like by firing `counter.run()`, this is very flexible; you can fire on a button click, in a timeout, any event you can think of really. But in your case, when something is in view, you could try this,

``` es6
let a = new Counter(opts1);
let elNode = document.getElementById('element-you-want-to-check-in-viewport')
window.addEventListener('scroll', () => {
 let el = elNode.getBoudingClientRect();

 if (el.top < 0)
    a.run();
});
```

Now, this is just an example, and will only check if you are scrolling form the top, i would suggest you checkout [this](https://github.com/jaxgeller/high-school-recruits-analytics/blob/master/www/src/js/meta.js#L33-L55), [this](https://github.com/jaxgeller/splitfix.js), or [this](http://stackoverflow.com/questions/8229291/how-to-check-if-an-element-is-in-the-view-of-the-user-with-jquery). It is also very inefficient to run events on scroll, i highly suggest running in a RAF for better performance, check out this article [here](http://www.html5rocks.com/en/tutorials/speed/animations/)
